[theme]
primaryColor = "#4A90E2"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false 